{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "OMN_OFFLINE",
    "contact": {}
  },
  "host": "api.omnadmin.xyz",
  "basePath": "/offline",
  "securityDefinitions": {},
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/challenger/create": {
      "post": {
        "description": "113.161.49.113:3000/offline/challenger/create",
        "summary": "api create challenger on offline type stand alone",
        "tags": [
          "Challenger"
        ],
        "operationId": "apicreatechallengeronofflinetypestandalone",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/apicreatechallengeronofflinetypestandalonerequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/challenger": {
      "get": {
        "description": "{{url}}/offline/challenger",
        "summary": "api get list challengerbelong to user",
        "tags": [
          "Challenger"
        ],
        "operationId": "apigetlistchallengerbelongtouser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/challenger/5f754c3631aaeb4e8bc7b609": {
      "get": {
        "description": "{{url}}/offline/challenger/5f62df7735e860e7ac9caecf",
        "summary": "api get detail challenger belong to user",
        "tags": [
          "Challenger"
        ],
        "operationId": "apigetdetailchallengerbelongtouser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/challenger/5ff411004e81e5020bac65e9": {
      "put": {
        "summary": "Update challanger for user",
        "tags": [
          "Challenger"
        ],
        "operationId": "Updatechallangerforuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdatechallangerforuserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/challenger/listProgramUpload": {
      "get": {
        "description": "{{url}}/offline/challenger",
        "summary": "api get list challenger upload for user",
        "tags": [
          "Challenger"
        ],
        "operationId": "apigetlistchallengeruploadforuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/challenger/listProgramApproval": {
      "get": {
        "description": "{{url}}/offline/challenger",
        "summary": "api get list challenger approval for user",
        "tags": [
          "Challenger"
        ],
        "operationId": "apigetlistchallengerapprovalforuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/challenger/{id}": {
      "delete": {
        "description": "{{url}}/offline/challenger/5f62df7735e860e7ac9caecf",
        "summary": "delete program",
        "tags": [
          "Challenger"
        ],
        "operationId": "deleteprogram",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/history-edit-program/upload/604700b460c73e01f7ed5b60": {
      "get": {
        "summary": "get list data backup",
        "tags": [
          "revert data"
        ],
        "operationId": "getlistdatabackup",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/history-edit-program/6048b25f4880cdcfaf080c50": {
      "get": {
        "description": "{{url}}/offline/history-edit-program/upload/604700b460c73e01f7ed5b60",
        "summary": "api get detail data back up upload",
        "tags": [
          "revert data"
        ],
        "operationId": "apigetdetaildatabackupupload",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/upload/revert-data/6048b25f4880cdcfaf080c50": {
      "put": {
        "description": "{{url}}/offline/upload/6048b25f4880cdcfaf080c50",
        "summary": "api revert old data",
        "tags": [
          "revert data"
        ],
        "operationId": "apirevertolddata",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/upload/create": {
      "post": {
        "summary": "api create upload on type season (Version 2)",
        "tags": [
          "Upload"
        ],
        "operationId": "apicreateuploadontypeseason(Version2)",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/apicreateuploadontypeseason%28Version2%29Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/upload": {
      "get": {
        "summary": "Get list upload belong to user",
        "tags": [
          "Upload"
        ],
        "operationId": "Getlistuploadbelongtouser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/upload/604700b460c73e01f7ed5b60": {
      "put": {
        "summary": "Update upload for user",
        "tags": [
          "Upload"
        ],
        "operationId": "Updateuploadforuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateuploadforuserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "description": "{{url}}/offline/challenger/5f62df7735e860e7ac9caecf",
        "summary": "api get detail upload for user",
        "tags": [
          "Upload"
        ],
        "operationId": "apigetdetailuploadforuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/upload/{id}": {
      "delete": {
        "description": "{{url}}/offline/challenger/5f62df7735e860e7ac9caecf",
        "summary": "delete program",
        "tags": [
          "Upload"
        ],
        "operationId": "Deletedeleteprogram",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/category-manage": {
      "get": {
        "description": "{{url}}/offline/category-manage/",
        "summary": "api get list category manage",
        "tags": [
          "category manage"
        ],
        "operationId": "apigetlistcategorymanage",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/category-manage/5fa919643eeb865eb4c2e82d": {
      "get": {
        "description": "{{url}}/offline/category-manage/5fa919643eeb865eb4c2e82d",
        "summary": "api get detail category manage",
        "tags": [
          "category manage"
        ],
        "operationId": "apigetdetailcategorymanage",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/program-sample/listProgramSample": {
      "get": {
        "description": "{{url}}/admin/manage/tag/create",
        "summary": "find program sample",
        "tags": [
          "program_sample"
        ],
        "operationId": "findprogramsample",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/omner/omniverse": {
      "get": {
        "summary": "Get user program in omniverse",
        "tags": [
          "OMNiverse"
        ],
        "operationId": "Getuserprograminomniverse",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/omner/result-letter": {
      "get": {
        "summary": "Get result letter by programID of omniverse",
        "tags": [
          "OMNiverse"
        ],
        "operationId": "GetresultletterbyprogramIDofomniverse",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "programID",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/omner/result-letter/5ff57b3d8458a002fd09b024": {
      "get": {
        "description": "{{url}}/offline/omner/result-letter/5ff57b1c8458a002fd09b023",
        "summary": "get detail message of omniverse",
        "tags": [
          "OMNiverse"
        ],
        "operationId": "getdetailmessageofomniverse",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/omner/my-program": {
      "get": {
        "description": "{{url}}/offline/omner/my-program",
        "summary": "api get user program in my program",
        "tags": [
          "MyProgram"
        ],
        "operationId": "apigetuserprograminmyprogram",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/omner/messages": {
      "get": {
        "summary": "Get messages",
        "tags": [
          "OtherMessage"
        ],
        "operationId": "Getmessages",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "title",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "category",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/omner/messages/{id}": {
      "get": {
        "summary": "Get detail message",
        "tags": [
          "OtherMessage"
        ],
        "operationId": "Getdetailmessage",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/rs-user/list-year/export": {
      "get": {
        "summary": "Export excel",
        "tags": [
          "PAYMENT"
        ],
        "operationId": "Exportexcel",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "year",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "month",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "apicreatechallengeronofflinetypestandalonerequest": {
      "title": "apicreatechallengeronofflinetypestandalonerequest",
      "example": {
        "programName": "test 7의 굴레 addd",
        "programImageTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Title/02_2021/25/4.Title_Image._1614238509png",
        "programSubTitle": "DC battle marvel",
        "programImagePoster": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Poster/02_2021/25/1.Poster_with_Title_1614238501.jpg",
        "programImagePosterNoTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/PosterNoTitle/02_2021/25/5.poster_without_title_1614238498.jpg",
        "programImageBracter": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Bracter/02_2021/25/3.bracters_Image_1614238513.jpg",
        "programSummary": "DC and marvel are together fighting the monster",
        "programCategory": {
          "categoryManageId": "5fa91d1bca45ac674dc9fff8",
          "categoryArrayTag": [
            "5fa913b862b7b45cee7046a4",
            "5fa917f23eeb865eb4c2e82c",
            "5fa91c61fffa646645c06737",
            "5fa92344c82c046d67873099",
            "5fa924c9c82c046d6787309a",
            "5faa07cca114d9e4522ffc82",
            "5faa07f9a114d9e4522ffc83"
          ]
        },
        "programElement": [
          {
            "elementName": "violence",
            "elementValue": "little"
          },
          {
            "elementName": "sexuality",
            "elementValue": "none"
          },
          {
            "elementName": "language",
            "elementValue": "plenty"
          }
        ],
        "programParticipants": [
          {
            "nameType": "Director",
            "dataType": [
              "rick",
              "joe"
            ]
          },
          {
            "nameType": "Main Actor",
            "dataType": [
              "jax",
              "matthew"
            ]
          },
          {
            "nameType": "Creator",
            "dataType": [
              "jin",
              "lee"
            ]
          }
        ],
        "programTypeVideo": "stand alone",
        "programEpisodeSummary": "batman cinema",
        "programThumbnail": {
          "thumbnailSetting": 150,
          "thumbnailImage": ""
        },
        "programVideoSetting": {
          "intro": 100,
          "outtro": 100
        },
        "programMusicInfo": [
          {
            "musicName": "i win in your heart",
            "musicArtist": "tony trungle"
          },
          {
            "musicName": "i hate you",
            "musicArtist": "adam levine"
          }
        ],
        "linkVideo": "https://omn-video-input.s3.ap-northeast-2.amazonaws.com/Challenger/11_12_2020/1080p_7_preview.mp4"
      },
      "type": "object",
      "properties": {
        "programName": {
          "type": "string"
        },
        "programImageTitle": {
          "type": "string"
        },
        "programSubTitle": {
          "type": "string"
        },
        "programImagePoster": {
          "type": "string"
        },
        "programImagePosterNoTitle": {
          "type": "string"
        },
        "programImageBracter": {
          "type": "string"
        },
        "programSummary": {
          "type": "string"
        },
        "programCategory": {
          "$ref": "#/definitions/ProgramCategory"
        },
        "programElement": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramElement"
          }
        },
        "programParticipants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramParticipant"
          }
        },
        "programTypeVideo": {
          "type": "string"
        },
        "programEpisodeSummary": {
          "type": "string"
        },
        "programThumbnail": {
          "$ref": "#/definitions/ProgramThumbnail"
        },
        "programVideoSetting": {
          "$ref": "#/definitions/ProgramVideoSetting"
        },
        "programMusicInfo": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramMusicInfo"
          }
        },
        "linkVideo": {
          "type": "string"
        }
      },
      "required": [
        "programName",
        "programImageTitle",
        "programSubTitle",
        "programImagePoster",
        "programImagePosterNoTitle",
        "programImageBracter",
        "programSummary",
        "programCategory",
        "programElement",
        "programParticipants",
        "programTypeVideo",
        "programEpisodeSummary",
        "programThumbnail",
        "programVideoSetting",
        "programMusicInfo",
        "linkVideo"
      ]
    },
    "ProgramCategory": {
      "title": "ProgramCategory",
      "example": {
        "categoryManageId": "5fa91d1bca45ac674dc9fff8",
        "categoryArrayTag": [
          "5fa913b862b7b45cee7046a4",
          "5fa917f23eeb865eb4c2e82c",
          "5fa91c61fffa646645c06737",
          "5fa92344c82c046d67873099",
          "5fa924c9c82c046d6787309a",
          "5faa07cca114d9e4522ffc82",
          "5faa07f9a114d9e4522ffc83"
        ]
      },
      "type": "object",
      "properties": {
        "categoryManageId": {
          "type": "string"
        },
        "categoryArrayTag": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "categoryManageId",
        "categoryArrayTag"
      ]
    },
    "ProgramElement": {
      "title": "ProgramElement",
      "example": {
        "elementName": "violence",
        "elementValue": "little"
      },
      "type": "object",
      "properties": {
        "elementName": {
          "type": "string"
        },
        "elementValue": {
          "type": "string"
        }
      },
      "required": [
        "elementName",
        "elementValue"
      ]
    },
    "ProgramParticipant": {
      "title": "ProgramParticipant",
      "example": {
        "nameType": "Director",
        "dataType": [
          "rick",
          "joe"
        ]
      },
      "type": "object",
      "properties": {
        "nameType": {
          "type": "string"
        },
        "dataType": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "nameType",
        "dataType"
      ]
    },
    "ProgramThumbnail": {
      "title": "ProgramThumbnail",
      "example": {
        "thumbnailSetting": 150,
        "thumbnailImage": ""
      },
      "type": "object",
      "properties": {
        "thumbnailSetting": {
          "type": "integer",
          "format": "int32"
        },
        "thumbnailImage": {
          "type": "string"
        }
      },
      "required": [
        "thumbnailSetting",
        "thumbnailImage"
      ]
    },
    "ProgramVideoSetting": {
      "title": "ProgramVideoSetting",
      "example": {
        "intro": 100,
        "outtro": 100
      },
      "type": "object",
      "properties": {
        "intro": {
          "type": "integer",
          "format": "int32"
        },
        "outtro": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "intro",
        "outtro"
      ]
    },
    "ProgramMusicInfo": {
      "title": "ProgramMusicInfo",
      "example": {
        "musicName": "i win in your heart",
        "musicArtist": "tony trungle"
      },
      "type": "object",
      "properties": {
        "musicName": {
          "type": "string"
        },
        "musicArtist": {
          "type": "string"
        }
      },
      "required": [
        "musicName",
        "musicArtist"
      ]
    },
    "apicreatechallengertypeseason(Version2)Request": {
      "title": "apicreatechallengertypeseason(Version2)Request",
      "example": {
        "programName": "CHALLENGER test season 1",
        "programImageTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Title/02_2021/25/4.Title_Image._1614238509png",
        "programSubTitle": "Prison break in usa",
        "programImagePoster": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Poster/02_2021/25/1.Poster_with_Title_1614238501.jpg",
        "programImageBracter": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/PosterNoTitle/02_2021/25/5.poster_without_title_1614238498.jpg",
        "programImagePosterNoTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Bracter/02_2021/25/3.bracters_Image_1614238513.jpg",
        "programSummary": "scofield want to help your brother freedom",
        "programCategory": {
          "categoryManageId": "5fa91d1bca45ac674dc9fff8",
          "categoryArrayTag": [
            "5fa913b862b7b45cee7046a4",
            "5fa915063eeb865eb4c2e821",
            "5fa916b73eeb865eb4c2e822",
            "5fa916ce3eeb865eb4c2e823",
            "5fa9172d3eeb865eb4c2e824",
            "5fa9177a3eeb865eb4c2e825",
            "5fa917873eeb865eb4c2e826",
            "5fa9179d3eeb865eb4c2e827",
            "5fa917ad3eeb865eb4c2e828",
            "5fa917b93eeb865eb4c2e829",
            "5fa917c13eeb865eb4c2e82a",
            "5fa917da3eeb865eb4c2e82b",
            "5fa917f23eeb865eb4c2e82c",
            "5fa91c61fffa646645c06737",
            "5fa92344c82c046d67873099",
            "5fa924c9c82c046d6787309a",
            "5faa07cca114d9e4522ffc82",
            "5faa07f9a114d9e4522ffc83"
          ]
        },
        "programElement": [
          {
            "elementName": "violence",
            "elementValue": "little"
          },
          {
            "elementName": "sexuality",
            "elementValue": "little"
          },
          {
            "elementName": "language",
            "elementValue": "plenty"
          }
        ],
        "programParticipants": [
          {
            "nameType": "Director",
            "dataType": [
              "Paul Scheuring",
              "quang"
            ]
          },
          {
            "nameType": "Main Actor",
            "dataType": [
              "dominic Purcell",
              "Wenworth Miller",
              "Amaury Nolasco",
              "Robert Knepper",
              "Sarah Wayne"
            ]
          },
          {
            "nameType": "Creator",
            "dataType": [
              "Louis",
              "Trang"
            ]
          }
        ],
        "programTypeVideo": "season",
        "programChildrenSeasonData": {
          "parentID": "5ffe9f700bd75a3ec4823966",
          "seasonName": "1",
          "episodeName": "Episode 3",
          "episodeSummary": "This is summary for episode 3",
          "linkVideo": "https://www.youtube.com/watch?v=05srvuuEWcU"
        },
        "programThumbnail": {
          "thumbnailSetting": 150,
          "thumbnailImage": ""
        },
        "programVideoSetting": {
          "intro": 100,
          "outtro": 100
        },
        "programEpisodeSummary": "batman",
        "programMusicInfo": [
          {
            "musicName": "OST prison break",
            "musicArtist": "adam lambert"
          },
          {
            "musicName": "without you",
            "musicArtist": "selena"
          }
        ],
        "linkVideo": "https://omn-video-input.s3.ap-northeast-2.amazonaws.com/Challenger/11_12_2020/1080p_7_preview.mp4"
      },
      "type": "object",
      "properties": {
        "programName": {
          "type": "string"
        },
        "programImageTitle": {
          "type": "string"
        },
        "programSubTitle": {
          "type": "string"
        },
        "programImagePoster": {
          "type": "string"
        },
        "programImageBracter": {
          "type": "string"
        },
        "programImagePosterNoTitle": {
          "type": "string"
        },
        "programSummary": {
          "type": "string"
        },
        "programCategory": {
          "$ref": "#/definitions/ProgramCategory"
        },
        "programElement": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramElement"
          }
        },
        "programParticipants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramParticipant"
          }
        },
        "programTypeVideo": {
          "type": "string"
        },
        "programChildrenSeasonData": {
          "$ref": "#/definitions/ProgramChildrenSeasonData"
        },
        "programThumbnail": {
          "$ref": "#/definitions/ProgramThumbnail"
        },
        "programVideoSetting": {
          "$ref": "#/definitions/ProgramVideoSetting"
        },
        "programEpisodeSummary": {
          "type": "string"
        },
        "programMusicInfo": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramMusicInfo"
          }
        },
        "linkVideo": {
          "type": "string"
        }
      },
      "required": [
        "programName",
        "programImageTitle",
        "programSubTitle",
        "programImagePoster",
        "programImageBracter",
        "programImagePosterNoTitle",
        "programSummary",
        "programCategory",
        "programElement",
        "programParticipants",
        "programTypeVideo",
        "programChildrenSeasonData",
        "programThumbnail",
        "programVideoSetting",
        "programEpisodeSummary",
        "programMusicInfo",
        "linkVideo"
      ]
    },
    "ProgramChildrenSeasonData": {
      "title": "ProgramChildrenSeasonData",
      "example": {
        "parentID": "5ffe9f700bd75a3ec4823966",
        "seasonName": "1",
        "episodeName": "Episode 3",
        "episodeSummary": "This is summary for episode 3",
        "linkVideo": "https://www.youtube.com/watch?v=05srvuuEWcU"
      },
      "type": "object",
      "properties": {
        "parentID": {
          "type": "string"
        },
        "seasonName": {
          "type": "string"
        },
        "episodeName": {
          "type": "string"
        },
        "episodeSummary": {
          "type": "string"
        },
        "linkVideo": {
          "type": "string"
        }
      },
      "required": [
        "parentID",
        "seasonName",
        "episodeName",
        "episodeSummary",
        "linkVideo"
      ]
    },
    "UpdatechallangerforuserRequest": {
      "title": "UpdatechallangerforuserRequest",
      "example": {
        "programName": "test-update-challenger-on-offline"
      },
      "type": "object",
      "properties": {
        "programName": {
          "type": "string"
        }
      },
      "required": [
        "programName"
      ]
    },
    "apicreateuploadontypeseason(Version2)Request": {
      "title": "apicreateuploadontypeseason(Version2)Request",
      "example": {
        "programName": "zzzz-test",
        "programImageTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Title/02_2021/25/4.Title_Image._1614238509png",
        "programSubTitle": "Prison break in usa",
        "programImagePoster": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Poster/02_2021/25/1.Poster_with_Title_1614238501.jpg",
        "programImagePosterNoTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/PosterNoTitle/02_2021/25/5.poster_without_title_1614238498.jpg",
        "programImageBracter": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Bracter/02_2021/25/3.bracters_Image_1614238513.jpg",
        "programSummary": "scofield want to help your brother freedom",
        "programCategory": {
          "categoryManageId": "5fa91d1bca45ac674dc9fff8",
          "categoryArrayTag": [
            "5fa913b862b7b45cee7046a4",
            "5fa915063eeb865eb4c2e821",
            "5fa916b73eeb865eb4c2e822",
            "5fa916ce3eeb865eb4c2e823",
            "5fa9172d3eeb865eb4c2e824",
            "5fa9177a3eeb865eb4c2e825",
            "5fa917873eeb865eb4c2e826",
            "5fa9179d3eeb865eb4c2e827",
            "5fa917ad3eeb865eb4c2e828",
            "5fa917b93eeb865eb4c2e829",
            "5fa917c13eeb865eb4c2e82a",
            "5fa917da3eeb865eb4c2e82b",
            "5fa917f23eeb865eb4c2e82c",
            "5fa91c61fffa646645c06737",
            "5fa92344c82c046d67873099",
            "5fa924c9c82c046d6787309a",
            "5faa07cca114d9e4522ffc82",
            "5faa07f9a114d9e4522ffc83"
          ]
        },
        "programElement": [
          {
            "elementName": "violence",
            "elementValue": "little"
          },
          {
            "elementName": "sexuality",
            "elementValue": "little"
          },
          {
            "elementName": "language",
            "elementValue": "plenty"
          }
        ],
        "programParticipants": [
          {
            "nameType": "Director",
            "dataType": [
              "Paul Scheuring",
              "quang"
            ]
          },
          {
            "nameType": "Main Actor",
            "dataType": [
              "dominic Purcell",
              "Wenworth Miller",
              "Amaury Nolasco",
              "Robert Knepper",
              "Sarah Wayne"
            ]
          },
          {
            "nameType": "Creator",
            "dataType": [
              "Louis",
              "Trang"
            ]
          }
        ],
        "programTypeVideo": "season",
        "programChildrenSeasonData": {
          "parentID": "",
          "seasonName": "1",
          "episodeName": "Episode 1",
          "episodeSummary": "This is summary for episode 1",
          "linkVideo": "https://www.youtube.com/watch?v=05srvuuEWcU"
        },
        "programThumbnail": {
          "thumbnailSetting": 150,
          "thumbnailImage": ""
        },
        "programVideoSetting": {
          "intro": 100,
          "preview": 100,
          "outtro": 100
        },
        "programEpisodeSummary": "batman",
        "programMusicInfo": [
          {
            "musicName": "OST prison break",
            "musicArtist": "adam lambert"
          },
          {
            "musicName": "without you",
            "musicArtist": "selena"
          }
        ],
        "linkVideo": "https://omn-video-input.s3.ap-northeast-2.amazonaws.com/02_2021/25/Episode01_1614239365.mp4"
      },
      "type": "object",
      "properties": {
        "programName": {
          "type": "string"
        },
        "programImageTitle": {
          "type": "string"
        },
        "programSubTitle": {
          "type": "string"
        },
        "programImagePoster": {
          "type": "string"
        },
        "programImagePosterNoTitle": {
          "type": "string"
        },
        "programImageBracter": {
          "type": "string"
        },
        "programSummary": {
          "type": "string"
        },
        "programCategory": {
          "$ref": "#/definitions/ProgramCategory"
        },
        "programElement": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramElement"
          }
        },
        "programParticipants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramParticipant"
          }
        },
        "programTypeVideo": {
          "type": "string"
        },
        "programChildrenSeasonData": {
          "$ref": "#/definitions/ProgramChildrenSeasonData"
        },
        "programThumbnail": {
          "$ref": "#/definitions/ProgramThumbnail"
        },
        "programVideoSetting": {
          "$ref": "#/definitions/ProgramVideoSetting2"
        },
        "programEpisodeSummary": {
          "type": "string"
        },
        "programMusicInfo": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramMusicInfo"
          }
        },
        "linkVideo": {
          "type": "string"
        }
      },
      "required": [
        "programName",
        "programImageTitle",
        "programSubTitle",
        "programImagePoster",
        "programImagePosterNoTitle",
        "programImageBracter",
        "programSummary",
        "programCategory",
        "programElement",
        "programParticipants",
        "programTypeVideo",
        "programChildrenSeasonData",
        "programThumbnail",
        "programVideoSetting",
        "programEpisodeSummary",
        "programMusicInfo",
        "linkVideo"
      ]
    },
    "ProgramVideoSetting2": {
      "title": "ProgramVideoSetting2",
      "example": {
        "intro": 100,
        "preview": 100,
        "outtro": 100
      },
      "type": "object",
      "properties": {
        "intro": {
          "type": "integer",
          "format": "int32"
        },
        "preview": {
          "type": "integer",
          "format": "int32"
        },
        "outtro": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "intro",
        "preview",
        "outtro"
      ]
    },
    "apicreateuploadontypestandalonerequest": {
      "title": "apicreateuploadontypestandalonerequest",
      "example": {
        "programName": "7의 굴레 addd",
        "programImageTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Title/02_2021/25/4.Title_Image._1614238509png",
        "programSubTitle": "DC battle marvel",
        "programImagePosterNoTitle": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Poster/02_2021/25/1.Poster_with_Title_1614238501.jpg",
        "programImagePoster": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/PosterNoTitle/02_2021/25/5.poster_without_title_1614238498.jpg",
        "programImageBracter": "https://omn-image-input.s3.ap-northeast-2.amazonaws.com/Upload/Bracter/02_2021/25/3.bracters_Image_1614238513.jpg",
        "programSummary": "DC and marvel are together fighting the monster",
        "programCategory": {
          "categoryManageId": "5fa91d1bca45ac674dc9fff8",
          "categoryArrayTag": [
            "5fa917c13eeb865eb4c2e82a",
            "5fa917da3eeb865eb4c2e82b",
            "5fa917f23eeb865eb4c2e82c",
            "5fa91c61fffa646645c06737",
            "5fa92344c82c046d67873099",
            "5fa924c9c82c046d6787309a",
            "5faa07cca114d9e4522ffc82",
            "5faa07f9a114d9e4522ffc83"
          ]
        },
        "programElement": [
          {
            "elementName": "violence",
            "elementValue": "little"
          },
          {
            "elementName": "sexuality",
            "elementValue": "none"
          },
          {
            "elementName": "language",
            "elementValue": "plenty"
          }
        ],
        "programParticipants": [
          {
            "nameType": "Director",
            "dataType": [
              "rick",
              "joe"
            ]
          },
          {
            "nameType": "Main Actor",
            "dataType": [
              "jax",
              "matthew"
            ]
          },
          {
            "nameType": "Creator",
            "dataType": [
              "jin",
              "lee"
            ]
          }
        ],
        "programTypeVideo": "stand alone",
        "programEpisodeSummary": "batman cinema",
        "programThumbnail": {
          "thumbnailSetting": 150,
          "thumbnailImage": ""
        },
        "programVideoSetting": {
          "intro": 100,
          "preview": 100,
          "outtro": 100
        },
        "programMusicInfo": [
          {
            "musicName": "i win in your heart",
            "musicArtist": "tony trungle"
          },
          {
            "musicName": "i hate you",
            "musicArtist": "adam levine"
          }
        ],
        "linkVideo": "https://omn-video-input.s3.ap-northeast-2.amazonaws.com/Challenger/11_12_2020/1080p_7_preview.mp4"
      },
      "type": "object",
      "properties": {
        "programName": {
          "type": "string"
        },
        "programImageTitle": {
          "type": "string"
        },
        "programSubTitle": {
          "type": "string"
        },
        "programImagePosterNoTitle": {
          "type": "string"
        },
        "programImagePoster": {
          "type": "string"
        },
        "programImageBracter": {
          "type": "string"
        },
        "programSummary": {
          "type": "string"
        },
        "programCategory": {
          "$ref": "#/definitions/ProgramCategory"
        },
        "programElement": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramElement"
          }
        },
        "programParticipants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramParticipant"
          }
        },
        "programTypeVideo": {
          "type": "string"
        },
        "programEpisodeSummary": {
          "type": "string"
        },
        "programThumbnail": {
          "$ref": "#/definitions/ProgramThumbnail"
        },
        "programVideoSetting": {
          "$ref": "#/definitions/ProgramVideoSetting2"
        },
        "programMusicInfo": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ProgramMusicInfo"
          }
        },
        "linkVideo": {
          "type": "string"
        }
      },
      "required": [
        "programName",
        "programImageTitle",
        "programSubTitle",
        "programImagePosterNoTitle",
        "programImagePoster",
        "programImageBracter",
        "programSummary",
        "programCategory",
        "programElement",
        "programParticipants",
        "programTypeVideo",
        "programEpisodeSummary",
        "programThumbnail",
        "programVideoSetting",
        "programMusicInfo",
        "linkVideo"
      ]
    },
    "UpdateuploadforuserRequest": {
      "title": "UpdateuploadforuserRequest",
      "example": {
        "programName": "7's bridle - test"
      },
      "type": "object",
      "properties": {
        "programName": {
          "type": "string"
        }
      },
      "required": [
        "programName"
      ]
    }
  },
  "tags": [
    {
      "name": "Challenger"
    },
    {
      "name": "revert data"
    },
    {
      "name": "Upload"
    },
    {
      "name": "category manage"
    },
    {
      "name": "program_sample"
    },
    {
      "name": "OMNiverse"
    },
    {
      "name": "MyProgram"
    },
    {
      "name": "OtherMessage"
    },
    {
      "name": "PAYMENT"
    }
  ]
}